version: '3.4'

services:
  webapplication1:
    image: ${DOCKER_REGISTRY-}webapplication1
    environment:
      - WebAppDemo_WelcomeMessage=Hello world (from docker-compose.yml)
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile